apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-configmap
  labels:
    env: dev
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'localhost'
        static_configs:
        - targets: ['localhost:9090']

      - job_name: 'redhat8'
        static_configs:
        - targets: ['192.168.43.93:9100']